// Testimonials from Change.org petition signers
// Selected for quality, diversity of location, and variety of perspectives

export interface Testimonial {
  quote: string;
  firstName: string;
  city: string;
  state: string;
}

export const TESTIMONIALS: Testimonial[] = [
  {
    quote: "This issue and the surrounding practice of unsolicited mailing upheld by the US postal service represents a major misallocation of our Nation's resources. Our forestry resources, petroleum resources, and the time of citizens who must sort through this daily deluge of unwanted paper.",
    firstName: "Carson",
    city: "Austin",
    state: "TX",
  },
  {
    quote: "It is beyond absurd that we are now FORCED by bully tactics to accept this ocean of unwanted junk mail. I live in an apartment and because six years ago the previous tenant ordered a service, I get weekly ads stuffed in my mailbox that I cannot stop.",
    firstName: "Donna",
    city: "Schenectady",
    state: "NY",
  },
  {
    quote: "I have a mountain of paperwork, and most of it is advertising mail. I shouldn't have to pay a 3rd party service to 'reduce' the advertising mail I receive. Most people throw away this mail without reading it—what a waste of resources!",
    firstName: "Kyle",
    city: "Kansas City",
    state: "MO",
  },
  {
    quote: "My mailbox is a local community type box. It is small and a few blocks away from my house so I do not check it every day. It has gotten overfilled and they took all the mail out and I had to go pick it up at the post office.",
    firstName: "Donna",
    city: "Saint Joseph",
    state: "MO",
  },
  {
    quote: "EDDM unsolicited mail wastes my time and hurts the environment. I do not want this mail. I should have the right to opt out of it.",
    firstName: "Don",
    city: "Olympia",
    state: "WA",
  },
  {
    quote: "It's all trash, trash, TRASH! Maybe if we all do our part and send the right people these messages, they'll realize the hassle of having to retrieve, sort, just to transfer such junk to the trash receptacle.",
    firstName: "Judge",
    city: "Chicago",
    state: "IL",
  },
  {
    quote: "I was injured and briefly hospitalized during late April. My mailbox became too full within 5 days due to junk. USPS stopped service. Even though I called and emailed to explain my injury, I was forced to go pick up mail at the post office.",
    firstName: "Eve",
    city: "Omaha",
    state: "NE",
  },
  {
    quote: "When I get unwanted junk mail like through EDDM, I usually go out of my way to make sure my family and I never give those solicitors our business. I also return everything to sender so they incur an additional cost.",
    firstName: "Albert",
    city: "Hialeah",
    state: "FL",
  },
  {
    quote: "ECRWSSEDDM is unacceptable harassment by USPS as a way of increased revenue. Fine them. Make it illegal. At least provide an opt-out. Postmasters do not listen, do not care.",
    firstName: "W",
    city: "Norwich",
    state: "CT",
  },
  {
    quote: "Right now as essential workers during the COVID-19 epidemic, postal workers are risking their lives for us. It doesn't sit well with me that they are risking their lives delivering junk mail that goes straight into the trash.",
    firstName: "Anthony",
    city: "Kingston",
    state: "NY",
  },
  {
    quote: "I've been asking Capital One to stop sending me offers for 2 years straight. Every few months when I get a new offer, I call them up, and they tell me to wait 40 days. Then I receive another offer.",
    firstName: "Thomas",
    city: "Myrtle Creek",
    state: "OR",
  },
  {
    quote: "USPS has been unjustly enriched on the backs of unsuspecting home owners not given a choice on what to receive in their mailboxes. USPS only cares about revenue to promote its crumbling operations.",
    firstName: "N",
    city: "West Palm Beach",
    state: "FL",
  },
  {
    quote: "Junk mail is a waste of time and goes directly in the trash. The junk mail may be what is keeping the Post Office in business as most communication is electronic.",
    firstName: "Nena",
    city: "Rome",
    state: "GA",
  },
  {
    quote: "Contributing with the intent to keep my inbox from being filled to the brim with unwanted and unsolicited junk. It's time for someone, ANYONE, to finally stop passing the buck and take responsibility for this.",
    firstName: "Glenn",
    city: "Laurel",
    state: "MD",
  },
  {
    quote: "It boggles the mind that there is no way to opt out. This should be the standard. I don't want to contribute to the wasteful production and transport of advertisements I'm going to throw out without reading.",
    firstName: "Paige",
    city: "Dubuque",
    state: "IA",
  },
  {
    quote: "I'm perplexed at how this is even still legal. The waste generated by the production of this garbage, only to immediately be thrown into the garbage and landfill, is mind boggling.",
    firstName: "Chris",
    city: "Plano",
    state: "TX",
  },
  {
    quote: "According to the Post Office, they 'aren't allowed' to not deliver these—even though it doesn't have an address on it, and even if the recipient says to not deliver them. This needs to STOP!",
    firstName: "Andy",
    city: "Clayton",
    state: "NC",
  },
  {
    quote: "I do not wish to support any agencies who send out reams upon reams of trash mail that is damaging to our environment, unwanted and unsolicited. You must demand a way to opt out of EDDM.",
    firstName: "Liz",
    city: "Avondale",
    state: "AZ",
  },
  {
    quote: "This system of mailing creates great waste and allows mailers to send potentially offensive material while providing receivers no way to opt out of receiving such material.",
    firstName: "Rob",
    city: "Evergreen",
    state: "CO",
  },
  {
    quote: "It is ridiculous how much junk mail I get, that ends up in the landfill. Please allow opting out, in order to save our treasure and environment, as well as my sanity.",
    firstName: "Lorri",
    city: "Elk Grove",
    state: "CA",
  },
  {
    quote: "Been trying to get off mailing lists for decades only to learn the USPS sells people's names to advertisers. They tell me it is the only way to make money.",
    firstName: "Warren",
    city: "Ledyard",
    state: "CT",
  },
  {
    quote: "I HATE the waste of paper and energy to send me solicitations for votes, money, purchases, charities. I will seek out my own information for my interests.",
    firstName: "Pat",
    city: "Santa Clara",
    state: "CA",
  },
  {
    quote: "Waste of trees and money in the digital age. You should be able to CHOOSE whether or not you want to receive junk mail, not have it forced upon you.",
    firstName: "Dan",
    city: "Buffalo",
    state: "NY",
  },
  {
    quote: "Because 100 million trees are cut down every year to produce the junk mail that almost all of us throw out. It's junk. Why would I support that?",
    firstName: "Jason",
    city: "North Bergen",
    state: "NJ",
  },
  {
    quote: "I want zero trash in my mailbox, and this mail is NEVER of any use to me. It only adds to the problems of dealing with waste in our environment.",
    firstName: "Sandra",
    city: "Decatur",
    state: "GA",
  },
];
